# -*- coding: utf-8 -*-
"""Energy Cost App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eK2Bup0c4SoesAKXv2jXTyPE2y-n4Xwq
"""

# Import necessary libraries
import streamlit as st
import numpy as np
import random
import pandas as pd

# Function to generate random coefficients
def generate_random_function():
    # Randomly generate coefficients for a sine and cosine combination
    a = random.uniform(-10, 10)
    b = random.uniform(-10, 10)
    c = random.uniform(-10, 10)
    return lambda x: a * np.sin(b * x) + c * np.cos(a * x)

# Streamlit app
st.title('Random Mathematical Functions Plot')

# Generate year range
years = np.linspace(2000, 2024, 25)  # From year 2000 to 2024

# Generate 5 random functions
functions = [generate_random_function() for _ in range(5)]

# Create a dictionary to hold function data
function_data = {}

# Calculate and store values for each function
for i, func in enumerate(functions, start=1):
    function_data[f'f{i}'] = func(years)

# Convert the dictionary to a DataFrame for better plotting
df = pd.DataFrame(function_data, index=years)

# Display the line chart
st.line_chart(df)