# -*- coding: utf-8 -*-
"""Energy Cost p2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1BGnnuqc-1f0ZDyERhxIrFx_Z36VJ1X
"""

# Import necessary libraries
import streamlit as st
import numpy as np
import pandas as pd

# Streamlit app
st.title('Custom Mathematical Functions Plot')

# Manually define the points for each function (you can replace these with your own values)
years = np.array([2017, 2018, 2019, 2020, 2021, 2022])

# Function 1: ARICD
f1_values = np.array([24.13, 27.04, 25.57, 22.34, 28.86, 36.02])

# Function 2: ARTCD
f2_values = np.array([26.5, 35.3, 54.8, 49.5, 52.1, 32.9])

# Function 3: ARTXD
f3_values = np.array([1.1, 0.9, 1.6, 1.3, 1.5, 3])

# Function 4: AVACD
f4_values = np.array([3, 4, 2, 2, 2, 15])

# Function 5: AVTCD
f5_values = np.array([0.7, 1.3, 1.8, 2.5, 4.1, 6.2])

# Create a dictionary to hold function data
function_data = {
    'ARICD': f1_values,
    'ARTCD': f2_values,
    'ARTXD': f3_values,
    'AVACD': f4_values,
    'AVTCD': f5_values
}

# Convert the dictionary to a DataFrame for better plotting
df = pd.DataFrame(function_data, index=years)

# Display the line chart with customized axes and labels
st.line_chart(df)

# Manually set axis labels (Streamlit automatically handles axis labels, but we can add some customizations)