# -*- coding: utf-8 -*-
"""Energy Cost p2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1BGnnuqc-1f0ZDyERhxIrFx_Z36VJ1X
"""

# Import necessary libraries
import streamlit as st
import pandas as pd

# Function to load CSV file and plot data
def load_and_plot_csv(uploaded_file):
    # Read the CSV file into a pandas DataFrame
    df = pd.read_csv(uploaded_file)

    # Assume that the years are in columns 1-6 (2017-2022)
    # and that the function values are in rows 2-6
    years = df.columns[1:]  # Get the years from columns 1 to 6 (2017 to 2022)

    # The function values are stored in rows 2 to 6 (Function 1 to Function 5)
    function_data = {
        'ARICD': df.iloc[0, 1:].values,   # Row 2, columns 2017-2022
        'ARTCD': df.iloc[1, 1:].values,   # Row 3, columns 2017-2022
        'ARTXD': df.iloc[2, 1:].values,   # Row 4, columns 2017-2022
        'AVACD': df.iloc[3, 1:].values,   # Row 5, columns 2017-2022
        'AVTCD': df.iloc[4, 1:].values    # Row 6, columns 2017-2022
    }

    # Convert the dictionary to a DataFrame
    df_plot = pd.DataFrame(function_data, index=years)

    # Display the line chart with the function data
    st.line_chart(df_plot)

# Streamlit app
st.title('CSV Data Plot for Functions')

# Upload CSV file
uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])

if uploaded_file is not None:
    # Load and plot the CSV data when file is uploaded
    load_and_plot_csv(uploaded_file)