# -*- coding: utf-8 -*-
"""Energy Cost p2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1BGnnuqc-1f0ZDyERhxIrFx_Z36VJ1X
"""

# Import necessary libraries
import streamlit as st
import numpy as np
import pandas as pd

# Streamlit app
st.title('Manually Plot Points for Functions')

# Manually define the years and function values
years = np.array([2017, 2018, 2019, 2020, 2021, 2022])

# Manually defined values for each function
f1_values = np.array([24.13, 27.04, 25.57, 22.34, 28.86, 36.02])  # f1 values
f2_values = np.array([26.5, 35.3, 54.8, 49.5, 52.1, 32.9])        # f2 values
f3_values = np.array([1.1, 0.9, 1.6, 1.3, 1.5, 3.0])              # f3 values
f4_values = np.array([3.0, 4.0, 2.0, 2.0, 2.0, 15.0])             # f4 values
f5_values = np.array([14.2, 15.0, 14.7, 16.0, 15.3, 15.5])        # f5 values

# Create a DataFrame for plotting
data = {
    'ARICD': f1_values,  # f1 values mapped to ARICD
    'ARTCD': f2_values,  # f2 values
    'ARTXD': f3_values,  # f3 values
    'AVACD': f4_values,  # f4 values
    'AVTCD': f5_values   # f5 values
}

# Create DataFrame for the years and function values
df = pd.DataFrame(data, index=years)

# Display the line chart
st.line_chart(df)

# Optionally, customize the plot's appearance further with markdown and CSS
st.markdown("""
    <style>