# -*- coding: utf-8 -*-
"""ENGERY P3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOoRo3GqYrIGP3OoSwG-0Fk3IAuiH5PT
"""

# Import necessary libraries
import streamlit as st
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt  # Importing matplotlib for plotting

# Streamlit app
st.title('Company Price Data Table and Plot')

# Function to generate random values for the table
def generate_random_data():
    companies = ['Company A', 'Company B', 'Company C', 'Company D', 'Company E', 'Company F']
    years = [2017, 2018, 2019, 2020, 2021, 2022]
    prices = [round(random.uniform(10, 100), 2) for _ in range(6)]  # Random price values between 10 and 100
    return companies, years, prices

# Generate random data
companies, years, prices = generate_random_data()

# Create a DataFrame for the table
df = pd.DataFrame({
    'Company': companies,
    'Year': years,
    'Price': prices
})

# Display the table in Streamlit
st.write("## Company Price Data Table")
st.dataframe(df)

# Plotting the data (plot the 'Price' over the 'Year' for each company)
plt.figure(figsize=(10, 6))

# Loop through the DataFrame and plot each company's data
for company in companies:
    company_data = df[df['Company'] == company]
    plt.plot(company_data['Year'], company_data['Price'], marker='o', label=company)

# Title and labels for the plot
plt.title('Company Price Over Years')
plt.xlabel('Year')
plt.ylabel('Price')
plt.legend()

# Display the plot in Streamlit
st.pyplot(plt)