# -*- coding: utf-8 -*-
"""Grades and Names on a Table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bt3froaL-2D-BY0km5xLpP5RI2PSiFfN
"""

import pandas as pd
import numpy as np

# List of names
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']

# Generate random grades between 0 and 100
grades = np.random.randint(0, 101, size=len(names))

# Create a DataFrame
grades_df = pd.DataFrame({
    'Names': names,
    'Grades': grades
})

# Set the title
print("Grades Table")
print(grades_df)